# -*- Makefile -*-
#
SRC_CFILES = consumption.c taboo.c uninterceptable_check.c revelations.c capture_by_invisible.c

INCLUDES = consumption.h taboo.h decisions.h uninterceptable_check.h revelations.h capture_by_invisible.h

include makefile.rules $(CURRPWD)depend
