# -*- Makefile -*-
#
CFILES = end_of_branch_goal_immobile.c immobility_tester_king_first.c

INCLUDES = end_of_branch_goal_immobile.h immobility_tester_king_first.h

include makefile.rules $(CURRPWD)depend
