# -*- Makefile -*-
#
SRC_CFILES = immobility_tester_king_first.c keepmating.c hash.c \
             orthodox_square_observation.c orthodox_check_directions.c \
             detect_retraction.c

INCLUDES = immobility_tester_king_first.h keepmating.h hash.h \
           orthodox_square_observation.h orthodox_check_directions.h \
           detect_retraction.h

include makefile.rules $(CURRPWD)depend
