# -*- Makefile -*-
#

SRC_CFILES = dht.c dhtcmem.c dhtmem.c dhtsimpl.c dhtstrng.c dhtvalue.c dhtbcmem.c \
	fxf.c
INCLUDES = dhtbcmem.h dhtcmem.h dht.h dhtmem.h dhtvalue.h fxf.h

include makefile.rules $(CURRPWD)depend
