# -*- Makefile -*-
#

ifeq ($(findstring DHT_OPEN_ADDRESSING,$(DEFS)),DHT_OPEN_ADDRESSING)
DHT_SRC = dht_open_addressing.c
else
DHT_SRC = dht.c
endif

SRC_CFILES = $(DHT_SRC) dhtcmem.c dhtmem.c dhtsimpl.c dhtstrng.c dhtvalue.c dhtbcmem.c \
	fxf.c
INCLUDES = dhtbcmem.h dhtcmem.h dht.h dhtmem.h dhtvalue.h fxf.h

include makefile.rules $(CURRPWD)depend
