# -*- Makefile -*-
#
SRC_CFILES = token.c pieces.c line.c input_stack.c twin.c \
             stipulation.c sstipulation.c goal.c condition.c option.c

INCLUDES = token.h pieces.h line.h input_stack.h twin.h \
           stipulation.h sstipulation.h goal.h condition.h option.h

include makefile.rules $(CURRPWD)depend
