# -*- Makefile -*-
#
SRC_CFILES = anticirce.c goal_filters.c target_square_filter.c \
           super.c capture_fork.c cheylan.c strict.c relaxed.c \
           magic_square.c
INCLUDES = anticirce.h goal_filters.h target_square_filter.h \
           super.h capture_fork.h cheylan.h strict.h relaxed.h \
           magic_square.h

include makefile.rules $(CURRPWD)depend
