# -*- Makefile -*-
#
SRC_CFILES = anticirce.c cheylan.c magic_square.c clone.c couscous.c capture_exchange.c
INCLUDES = anticirce.h cheylan.h magic_square.h clone.h couscous.h capture_exchange.h

include makefile.rules $(CURRPWD)depend
