# -*- Makefile -*-
#
CFILES = orthodox_mating_moves_generation.c orthodox_mating_move_generator.c orthodox_mating_move_fork.c

INCLUDES = orthodox_mating_moves_generation.h orthodox_mating_move_generator.h orthodox_mating_move_fork.h

include makefile.rules $(CURRPWD)depend
