# -*- Makefile -*-
#
SRC_CFILES = orthodox_mating_moves_generation.c \
             orthodox_mating_move_generator.c king_contact_move_generator.c

INCLUDES = orthodox_mating_moves_generation.h \
           orthodox_mating_move_generator.h king_contact_move_generator.h

include makefile.rules $(CURRPWD)depend
