# -*- Makefile -*-
#
SRC_CFILES = side_change.c walks.c hunters.c roses.c marine.c vectors.c

INCLUDES = side_change.h walks.h hunters.h roses.h marine.h vectors.h

include makefile.rules $(CURRPWD)depend
