# -*- Makefile -*-
#
CFILES = branch.c attack_root.c attack_move.c attack_play.c \
	defense_root.c defense_move.c defense_play.c
INCLUDES = branch.h attack_root.h attack_move.h attack_play.h \
	defense_root.h defense_move.h defense_play.h

include makefile.rules $(CURRPWD)depend
