# -*- Makefile -*-
#
CFILES = branch.c proxy.c leaf.c setplay_fork.c  reflex_attack_solver.c
INCLUDES = branch.h proxy.h leaf.h setplay_fork.h reflex_attack_solver.h

include makefile.rules $(CURRPWD)depend
