# -*- Makefile -*-
#
CFILES = finish.c filter.c immobilise_black.c deal_with_unused_pieces.c white_block.c black_block.c pin_black_piece.c goalreachable_guard.c
INCLUDES = finish.h filter.h immobilise_black.h deal_with_unused_pieces.h black_block.h white_block.h pin_black_piece.h goalreachable_guard.h

include makefile.rules $(CURRPWD)depend
