# -*- Makefile -*-
#
CFILES = finish.c filter.c immobilise_black.c deal_with_unused_pieces.c white_block.c black_block.c pin_black_piece.c intercept_checks_to_white.c intercept_checks_to_black.c goalreachable_guard.c
INCLUDES = finish.h filter.h immobilise_black.h deal_with_unused_pieces.h black_block.h white_block.h pin_black_piece.h intercept_checks_to_white.h intercept_checks_to_black.h goalreachable_guard.c

include makefile.rules $(CURRPWD)depend
