# -*- Makefile -*-
#
SRC_CFILES = pawn.c pawns.c promotee_sequence.c promotion.c en_passant.c reverse.c berolina.c super.c combined.c

INCLUDES = pawn.h pawns.h promotee_sequence.h promotion.h en_passant.h reverse.h berolina.h super.h combined.h

include makefile.rules $(CURRPWD)depend
