# -*- Makefile -*-
#
CFILES = branch.c root.c move.c move_to_goal.c dummy_move.c fork.c parry_fork.c shortcut.c play.c

INCLUDES = branch.h root.h move.h move_to_goal.h dummy_move.h fork.h parry_fork.h shortcut.h play.h

include makefile.rules $(CURRPWD)depend
