# -*- Makefile -*-
#
SRC_CFILES =  continuation.c check_detector.c threat.c try.c setplay.c \
          min_length_optimiser.c min_length_guard.c attack_play.c defense_play.c
INCLUDES =  continuation.h check_detector.h threat.h try.h setplay.h \
            min_length_optimiser.h min_length_guard.h attack_play.h defense_play.h

include makefile.rules $(CURRPWD)depend
