# -*- Makefile -*-
#
CFILES = stoponshortsolutions.c \
	root_solvable_filter.c help_filter.c series_filter.c

INCLUDES = stoponshortsolutions.h \
	root_solvable_filter.h help_filter.h series_filter.h

include makefile.rules $(CURRPWD)depend
