# -*- Makefile -*-
#
CFILES = adapter.c branch.c find_shortest.c root.c ready_for_help_move.c move.c move_to_goal.c shortcut.c fork.c play.c
INCLUDES = adapter.h branch.h find_shortest.h root.h ready_for_help_move.h move.h move_to_goal.h shortcut.h fork.h play.h

include makefile.rules $(CURRPWD)depend
