# -*- Makefile -*-
#

CFILES = plaintext.c end_of_phase_writer.c illegal_selfcheck_writer.c move_inversion_counter.c  trivial_end_filter.c

INCLUDES = plaintext.h end_of_phase_writer.h illegal_selfcheck_writer.h move_inversion_counter.h trivial_end_filter.h

include makefile.rules $(CURRPWD)depend
