# -*- Makefile -*-
#

SRC_CFILES = plaintext.c end_of_phase_writer.c illegal_selfcheck_writer.c \
             move_inversion_counter.c ohneschach_detect_undecidable_goal.c \
             goal_writer.c language_dependant.c

INCLUDES = plaintext.h end_of_phase_writer.h illegal_selfcheck_writer.h \
           move_inversion_counter.h ohneschach_detect_undecidable_goal.h \
           goal_writer.h language_dependant.h

include makefile.rules $(CURRPWD)depend
